name: "Run install.doctor on Pull Requests"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run_installer:
    name: Run install.doctor on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          uname -a || true

      - name: Run install.doctor installer
        shell: bash
        env:
          CI: true
        run: |
          echo "Running install.doctor installer"
          bash <(curl -sSL https://install.doctor/start)
